### ISSUE TITLE
Have a Look ! I can help you out with anything! Literally anything!

### ISSUE THREAD

**Issue by SparkScratch-P** [derter-menter/derter-menter.github.io#13]
# Glad to Help!

See, U said u need help and see my sites first; I can help you out with anything! Say what you need, and I am on it! 

## Profile Readme:  [github.com/SparkScratch-P](https://github.com/SparkScratch-P)

**Comment by derter-menter** [comment]
If you know how to make a button to toggle dark mode then that will be great, I already made the dark mode CSS file

**Comment by SparkScratch-P** [comment]
## I will try to do that for sure!

```

<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {
  padding: 25px;
  background-color: white;
  color: black;
  font-size: 25px;
}

.dark-mode {
  background-color: black;
  color: white;
}
</style>


<button onclick="myFunction()">Toggle dark mode</button>

<script>
function myFunction() {
   var element = document.body;
   element.classList.toggle("dark-mode");
}
</script>

```

**Comment by SparkScratch-P** [comment]
## Thanks for merging my request. You can also use many of my tools, and shields to modify your site, and feel free to ask for any help. DOn't forget to star your website repo in mine... and a few more if you like. Follow me for more exciting projects!

### If u want..it's my theme... u can add this too!
![d](https://github-readme-stats.vercel.app/api?username=derter-menter&title_color=53b14f&icon_color=53b14f&text_color=b3b3b3&bg_color=121212&show_icons=true)

**Comment by derter-menter** [comment]
Thanks for the help, I have removed the button for now since the layout got ruined in the process. Thanks for your help.

The dark file is linked here - dark.html

You can see what I want the dark mode to be here: https://derter-menter.github.io/dark/

**Comment by SparkScratch-P** [comment]
## Fixed, Check out now. I have changed the entire thing, integrated it into only one file- `inde.html`, but if u want a button, check out from [sparkscratch-p.github.io/CSS-Animation-Buttons/](https://sparkscratch-p.github.io/CSS-Animation-Buttons/library/) and say, I will put that there!
